services:

  db:
    image: postgres:17-alpine
    container_name: postgresDB
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB:?err}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}
      POSTGRES_USER: ${POSTGRES_USER:?err}
    healthcheck:
          test: [CMD-SHELL, "sh -c 'pg_isready -U ${POSTGRES_USER} --dbname ${POSTGRES_DB}'"]
          interval: 10s
          timeout: 5s
          retries: 5
    volumes:
      - postgresDB:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d
    networks:  
      - etl_net

  # app:
  #   container_name: neoflex_etl_proj
  #   build:
  #     context: ./
  #     dockerfile: ./dockerfiles/app.Dockerfile
  #   environment:
  #     DATABASE_DS_URL: ${DATABASE_DS_URL:?err}
  #     DATABASE_LOGGER_URL: ${DATABASE_LOGGER_URL:?err}
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   networks:  
  #     - etl_net


volumes:
  postgresDB:


networks:
  etl_net:
